### ISSUE TITLE
BetaNet Wallet Deploy

### ISSUE THREAD

**Issue by john-harmony** [harmony-one/dapp-examples#1]
**Overview**

Want to deploy a hosted web wallet for Betanet

**Background Information**
For current deployment please read the [Harmony Software Development Kit](https://docs.harmony.one/sdk-wiki/)

**Task Overview**
- [ ] Deploy a local web wallet pointing to BetaNet
- [ ] Update the SDK with instructions
- [ ] Deploy a hosted version of the web Wallet connecting to BetaNet
- [ ] Update the SDK Instructions

**Acceptance Criteria**
- [ ] You can do a transfer of funds on local instance of BetaNet
- [ ] You can do a transfer of funds on hosted instance of BetaNet
- [ ] Someone can follow the instructions to deploy BetaNet
