### ISSUE TITLE
WebWallet - provide the ability to import and export privateKeys

### ISSUE THREAD

**Issue by john-harmony** [harmony-one/dapp-examples#2]
**Overview**
For developers require the ability to also manage private keys

**Background**
Please read the [Harmony Developers Guide](https://docs.harmony.one/sdk-wiki/)

**Tasks**
- [ ] Provide the ability to display private key
- [ ] Provide the ability to import private key from an encrypted key file
- [ ] Provide the ability to import private key from text

Optional
- [ ] Provide a more secure storage mechanism for private keys

**Acceptance Criteria**
- [ ] A private key can be displayed
- [ ] A private key can be added via an encrytped key file
- [ ] A private key can be imported by inputting the text
