### ISSUE TITLE
WebWallet - Improve look and feel, usability and add Harmony Branding

### ISSUE THREAD

**Issue by john-harmony** [harmony-one/dapp-examples#3]
**Overview**
The WebWallet will be used by developers and can be enhanced for better usability and harmony branding.

**Background Material** 
Please review the [Harmony Developer Guide](https://docs.harmony.one/sdk-wiki/)

**Tasks**

**Acceptance Criteria**
- [ ] All functionality works
  - [ ] Wallet Creation
  - [ ] Wallet Recovery by passphrase
  - [ ] Adding accounts
  - [ ] Private Key Management (importing and displaying)
  - [ ] Transfer of Funds
- [ ] Branding signed off by Marketing
- [ ] Look and feel reviewed and approved
